#release configuration
#Sun Apr 05 15:54:35 CEST 2026
completedPhase=check-poms
exec.additionalArguments=-P\!dev
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.com.github.stefanofornari\:formsfx-demo.empty=true
project.scm.com.github.stefanofornari\:formsfx.empty=true
project.scm.com.github.stefanofornari\:formsfxparent.connection=scm\:git\:git@github.com\:stefanofornari/formsfx.git
project.scm.com.github.stefanofornari\:formsfxparent.tag=HEAD
project.scm.com.github.stefanofornari\:formsfxparent.url=https\://github.com/stefanofornari/formsfx
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:stefanofornari/formsfx.git
