#release configuration
#Sun May 31 17:04:06 CEST 2026
completedPhase=end-release
exec.activateProfiles=ossrh,release
exec.additionalArguments=-P\!dev
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.github.stefanofornari\:formsfx=26.0.3-SNAPSHOT
project.dev.com.github.stefanofornari\:formsfxparent=26.0.3-SNAPSHOT
project.rel.com.github.stefanofornari\:formsfx=26.0.2
project.rel.com.github.stefanofornari\:formsfxparent=26.0.2
project.scm.com.github.stefanofornari\:formsfx-demo.empty=true
project.scm.com.github.stefanofornari\:formsfx.empty=true
project.scm.com.github.stefanofornari\:formsfxparent.connection=scm\:git\:git@github.com\:stefanofornari/formsfx.git
project.scm.com.github.stefanofornari\:formsfxparent.tag=formsfxparent-26.0.2
project.scm.com.github.stefanofornari\:formsfxparent.url=https\://github.com/stefanofornari/formsfx
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=formsfxparent-26.0.2
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:stefanofornari/formsfx.git
